enum Modes {
    DRAWING_MODE,
    HEART_ANIMATION_MODE,
    FACE_ANIMATION_MODE,
    BULB_ANIMATION_MODE,
    LIGHT_MODE,
    BULB_MODE,
    STRAWBERRY_MODE,
    PINEAPPLE_MODE,
    CYLON_ANIMATION_MODE
};